[tool.poetry]
name = "repl_python3_cogs-adder"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.2"
pymongo = "^3.12.1"
discord = "^1.7.3"
dnspython = "^2.1.0"
srv = "^1.1.0"
"akinator.py" = "^5.0.0"
DiscordUtils = "^1.3.4"
youtube_dl = "^2021.6.6"
discord-components = "^2.1.2"
replit = "^3.2.4"
PyNaCl = "^1.4.0"
googletrans = "^3.1.0a0"
pytz = "^2021.3"
dblpy = "^0.4.0"
google-api-client = "^3.14.159265359"
google-api-python-client = "^2.30.0"
python-dotenv = "^0.19.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
